### ISSUE TITLE
Not up yet?

### ISSUE THREAD

**Issue by kentcdodds** [bevacqua/twitter-for-github#1]
<img width="494" alt="screen shot 2016-03-23 at 9 13 43 pm" src="https://cloud.githubusercontent.com/assets/1500684/14007421/2b0e5f34-f13c-11e5-87c7-083cedb8c4b8.png">

Am I just too fast?

**Comment by bevacqua** [comment]
You are just too fast. Also, take it up with Google, haha!

<img width="986" alt="screen shot 2016-03-24 at 00 15 11" src="https://cloud.githubusercontent.com/assets/934293/14007441/8080fd0a-f155-11e5-9250-50fd6c25543c.png">

**Comment by kentcdodds** [comment]
Yup, I was too fast.

<img width="1017" alt="screen shot 2016-03-23 at 9 15 19 pm" src="https://cloud.githubusercontent.com/assets/1500684/14007442/5fc4d80c-f13c-11e5-9644-35867ccb36eb.png">
