### ISSUE TITLE
Cannot find my twitter?

### ISSUE THREAD

**Issue by kentcdodds** [bevacqua/twitter-for-github#2]
I'm not sure what's going wrong here because even if I hit `https://get-twitter-username.herokuapp.com/kentcdodds` manually I get my correct twitter username. But this extension fails to find my twitter account and add it to my profile page :-(

<img width="256" alt="screen shot 2016-03-23 at 9 20 01 pm" src="https://cloud.githubusercontent.com/assets/1500684/14007515/0c8608ae-f13d-11e5-9bab-c1d6d49092f6.png">

**Comment by sindresorhus** [comment]
Same with https://get-twitter-username.herokuapp.com/paulirish and https://get-twitter-username.herokuapp.com/passy.

**Comment by kentcdodds** [comment]
Actually, it looks like those two return nothing, mine actually does return my twitter username.

**Comment by ahmedelgabri** [comment]
Same here too https://get-twitter-username.herokuapp.com/ahmedelgabri

**Comment by kentcdodds** [comment]
Just to make sure and clarify, I think that @sindresorhus and @ahmedelgabri have found totally different bugs than the one I originally reported. https://get-twitter-username.herokuapp.com/kentcdodds actually returns the correct twitter handle, but that handle doesn't appear on the github profile.

All of these:
https://get-twitter-username.herokuapp.com/paulirish
https://get-twitter-username.herokuapp.com/passy
https://get-twitter-username.herokuapp.com/ahmedelgabri

return nothing. Different bug entirely.

**Comment by UltCombo** [comment]
I'm experiencing the same bug as @kentcdodds. The web service returns my Twitter handle correctly correctly (https://get-twitter-username.herokuapp.com/UltCombo) but the extension does not display it in my [GitHub profile](https://github.com/UltCombo).

**Comment by UltCombo** [comment]
Submitted a fix here: #4

**Comment by kentcdodds** [comment]
Sweet! Fixed for me. Thanks @UltCombo!
